const data = [
  {
    nome: "Bicicleta S-Works Tarmac SL8 ",
    valor: "119900,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94924-00_TARMAC-SL8-SW-DI2-FOGTNT-GRNGSTPRL-REDGSTPRL_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 1,
  },
  {
    nome: "Bicicleta Roubaix SL8",
    valor: "21990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94423-70_ROUBAIX-RSTDRED-OBSD_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 2,
  },
  {
    nome: "Bicicleta Roubaix SL8 Comp",
    valor: "42990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94423-52_ROUBAIX-COMP-DPLAKEMET-METWHTSGE_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 3,
  },
  {
    nome: "Bicicleta S-Works Roubaix SL8",
    valor: "114900,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94423-00_ROUBAIX-SW-SMK-BLKPRL_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 4,
  },
  {
    nome: "Bicicleta Diverge E5",
    valor: "10990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-70_DIVERGE-E5-CSTBTLSHP-SILDST-CHRM_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 5,
  },
  {
    nome: "Bicicleta Diverge Comp E5",
    valor: "19990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-52_DIVERGE-E5-COMP-SPR-OAKGRNMET-CHRM_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 6,
  },
  {
    nome: "Bicicleta Diverge Sport Carbon ",
    valor: "28490,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-61_DIVERGE-SPORT-CARBON-LMSTN-BLK-CHRM_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 7,
  },
  {
    nome: "Bicicleta Diverge Sport Carbon 2",
    valor: "29990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95423-60_DIVERGE-SPORT-CARBON-MORNMST-DOVGRY_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 8,
  },
  {
    nome: "Bicicleta Diverge Comp Carbon",
    valor: "39990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-50_DIVERGE-COMP-CARBON-GUN-WHT-CHRM_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 9,
  },
  {
    nome: "Bicicleta Diverge Expert Carbon",
    valor: "49990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-30_DIVERGE-EXPERT-CARBON-ARCTBLU-SND-TRCTA_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 10,
  },
  {
    nome: "Bicicleta Diverge STR Expert",
    valor: "59990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/96223-30_DIVERGE-STR-EXPERT-BLK-DMNDDST_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 11,
  },
  {
    nome: "Bicicleta S-Works Diverge",
    valor: "107990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/95422-00_DIVERGE-SW-LTSIL-DRMSIL-DSTBLU_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 12,
  },
  {
    nome: "Bicicleta S-Works Diverge STR",
    valor: "119990,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/96223-00_DIVERGE-STR-SW-FSTGRN-DKMOS-BLKPRL_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 13,
  },
  {
    nome: "Bicicleta Allez",
    valor: "8790,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94622-70_ALLEZ-E5-BLK-CSTBTLSHP-CARB_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 14,
  },
  {
    nome: "Bicicleta Allez Sport",
    valor: "10790,00",
    quantidade: 1,
    foto: "https://assets.specialized.com/i/specialized/94622-62_ALLEZ-E5-SPORT-PNGRN-METGLD-CARB_HERO?$scom-pdp-product-image$&fmt=auto",
    id: 15,
  },
];
export default data;
